apiVersion: apps/v1
kind: Deployment
metadata:
  name: esp
  labels:
    app: esp
spec:
  replicas: 0
  selector:
    matchLabels:
      app: esp
  strategy:
      rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: esp
    spec:
      imagePullSecrets:
      - name: dockerkey
      containers:
      - name: esp
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2048Mi"
            cpu: "500m"
          limits:
            memory: "8Gi"
            cpu: "1"
        ports:
        - containerPort: 50051
          name: grpc-exp
        env:
          - name: OMP_NUM_THREADS
            value: "1"
          - name: MODEL_SERVICE_GRPC_INTERFACE
            valueFrom:
              secretKeyRef:
                name: esp-secrets-25kf4ff872
                key: MODEL_SERVICE_GRPC_INTERFACE
          - name: MODEL_SERVICE_GRPC_PORT
            valueFrom:
              secretKeyRef:
                name: esp-secrets-25kf4ff872
                key: MODEL_SERVICE_GRPC_PORT
          - name: ESP_MODELS_BUCKET
            valueFrom:
              secretKeyRef:
                name: esp-secrets-25kf4ff872
                key: ESP_MODELS_BUCKET
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: esp-secrets-25kf4ff872
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: esp-secrets-25kf4ff872
                key: AWS_SECRET_ACCESS_KEY
