commonAnnotations:
    note: This is the production blue environment with V3 of the service
nameSuffix: -v3.blue
namespace: es
resources: 
  - ../../../base
patchesStrategicMerge:
  - deployment.yaml
